backend/src/lib.rs, backend/src/shortcuts.rs, web/package-lock.json, web/package.json, web/src/AnimatePaths.svelte, web/src/common/zorder.ts, web/src/edit/NeighbourhoodMode.svelte, web/src/stores.ts
I was trying to make the changes in shortcut colors animated for #46, but it looks like maplibre can't combine transitions with data-driven styles. So instead, I wound up trying another idea to visualize which shortcuts are the most used. It's maybe distracting in editing mode -- it's opt-out right now, but will reconsider.
https://github.com/dabreegster/ltn/assets/1664407/97fcce61-3bf3-4e93-9669-80b7ab627594
=> Animate shortcuts

web/src/DebugDemandMode.svelte, web/src/common/colors.ts, web/src/wasm.ts
#36 
[Screencast from 09-02-25 14:26:17.webm](https://github.com/user-attachments/assets/1f0f150f-c2a6-4d97-aef8-f07f686e0122)
I'm mostly trying to mimick the good ol' commuter patterns from A/B Street. Does it seem reasonably understandable so far?
=> Use a choropleth to show OD zone demand

web/src/stores.ts
Part of #117 
I don't think this is the end of this work, but makes it a little less annoying in the meanwhile.
=> Remove automatic "about" splash

web/src/PickNeighbourhoodMode.svelte
[Screencast from 21-02-25 10:13:47.webm](https://github.com/user-attachments/assets/a7822fea-d14a-47cc-bfa2-642d8555fdf4)
Also refactor to one FillLayer
=> Highlight the neighbourhood on the map when hovering on an item in the sidebar

.gitmodules, bin/download-local-dev-data.sh, data_prep/scotland/get_reference_layers.sh, web/src/common/zorder.ts, web/src/context/ContextualLayers.svelte, web/src/context/Stats19.svelte
#106 
Most code and styling decisions are lifted from https://github.com/acteng/atip-data-prep/ and https://github.com/acteng/atip.
=> Add a stats19 contextual layer.

web/src/AutoBoundariesMode.svelte, web/src/PickNeighbourhoodMode.svelte, web/src/prioritization/PrioritizationSelect.svelte, web/src/prioritization/index.ts
Some of the items that came out of our meeting were very small and straight forward. 
For those I'm going to open PRs directly rather than first write up an issues. 
LMK if you'd like me to do otherwise - I should be done with them within the hour.
=> Remove SIMD popup

web/src/PickNeighbourhoodMode.svelte, web/src/Settings.svelte, web/src/edit/NeighbourhoodMode.svelte, web/src/stores.ts
=> Hide some controls behind a dev mode setting

backend/src/auto_boundaries.rs, backend/src/lib.rs, web/src/AutoBoundariesMode.svelte
FIXES #208 
**Before:**
https://github.com/user-attachments/assets/9b9f3c72-585b-4f3d-9c21-57f6ff43c0bc
**After:**
https://github.com/user-attachments/assets/94803914-9d6a-4a1a-8771-750062a4ea4c
=> Merge boundaries across "slivers"

web/src/common/ProjectStorage.ts, web/src/title/TitleMode.svelte, web/src/title/loader.ts, web/src/wasm.ts
Small non-behavioral changes, following up on your feedback in #244
=> synthetic db keys followups

web/src/AddNeighbourhoodMode.svelte, web/src/common/NeighbourhoodBoundarySummary.svelte, web/src/common/draw_area/AreaControls.svelte
Followup to #246 
FIXES #256 
I recommend pulling down  the code and running it to test out. It's somewhat interactive and hard to evaluate in screenshots.
**initially:**
**after choosing one:** we mark "step 1" as complete. You can add more or finish.
**after choosing two+:** we mark "step 2" as complete
**after drawing a valid boundary:** you can continue to adjust or finish.
---
Maybe also resolves:
>  I managed to get partly stuck by clicking pregenerated boundaries and merging them, then switching to manual drawing, then switching back to areas, then back to manual. Manual mode didn't have a "Finish / start over" button. I'll repro more carefully next and/or just fix if it's quick.
By offering better hints and keeping the "start over" button available during draw mode, even when you …
=> UI followups to the "add neighborhood" flow

backend/src/auto_boundaries.rs
#262 accidentally broke small study areas, treating the one boundary polygon as an island. Fix by just seeing if the study area boundary is actually a multipolygon before checking for small islands.
Tested in the global version prebuilt areas like Montlake and Elephant & Castle
=> Only filter out 'islands' when the input boundary is a multipolygon

web/assets/one_way_left.svg, web/src/About.svelte, web/src/edit/NeighbourhoodMode.svelte
Fixes #200 
If I recall correctly, this conversation might have happened during the meeting when you were having network troubles - but we talked about how the "travel flow" tools purpose wasn't immediately obvious.
**before**
**after**
=> Cleared "one way" button

backend/src/create.rs, backend/src/lib.rs, backend/src/map_model.rs, backend/src/neighbourhood.rs
=> Fix undo/redo

web/src/About.svelte
=> Rewrite project credits

backend/benches/router.rs, backend/src/impact.rs, backend/src/lib.rs, backend/src/map_model.rs, backend/src/neighbourhood.rs, backend/src/route.rs, backend/src/shortcuts.rs
Preparation for #243, internally changing the API to route from more accurate positions along a road and plumbing the necessary router input everywhere. There shouldn't be any behavioral diff yet, but the API change is big enough to warrant a first PR to make the second easier to understand.
=> Refactor to prepare for more accurate routing

web/src/edit/NeighbourhoodMode.svelte
Followup to https://github.com/a-b-street/ltn/pull/293#discussion_r2025674459
=> fix icons for production deployment

backend/src/map_model.rs, backend/src/route.rs
FIXES #243
A route no longer crosses the entirety of the first and last road; it starts at a precise position along it. That lets us travel only one direction when we start or end on a filtered road.
The code complexity here is more than I would've liked. There's subtleties I've tried to comment. Right now, the only tests are me manually playing around in the route mode. If we're going to merge this without real tests, please also play around and try to break it.
Just demonstrating precise positions, including loop roads:
[Screencast from 03-04-25 17:22:45.webm](https://github.com/user-attachments/assets/ae80d5b1-7988-4d4e-815b-87d017b93974)
Starting on a filtered road:
[Screencast from 03-04-25 18:02:44.webm](https://github.com/user-attachments/assets/983c0211-d70f-4dcf-b5db-f826d8c16e13) …
=> Route from precise positions along roads, and handle starting or ending on a filtered road

Cargo.lock, Cargo.toml, data_prep/scotland/src/bin/generate_prioritization.rs
~~Depends on https://github.com/dabreegster/route_snapper/pull/61, so review that first.~~ 
*Update:* merged!
=> update to latest geo

backend/benches/impact.rs, backend/benches/router.rs, backend/src/create.rs, backend/src/impact.rs, backend/src/lib.rs, backend/src/map_model.rs, backend/src/od.rs, backend/src/route.rs, data_prep/scotland/src/bin/generate_od.rs, web/src/AddNeighbourhoodMode.svelte, web/src/ImpactDetailMode.svelte, web/src/PredictImpactMode.svelte, web/src/common/Loading.svelte, web/src/common/index.ts, web/src/title/NewProjectMode.svelte, web/src/title/TitleMode.svelte
Some progress on #129 - I'd say this covers the low and medium hanging fruit anyway.
There's a few fundamental changes here, which I'll call out in line.
I'm going to leave these commits unsquashed for now in case you were curious or, if some of the changes are controversial, to make them more easily removable.
=> improve predict impact perf

backend/src/geo_helpers/mod.rs, backend/src/map_model.rs
Previously it only looked good for intersections with ~90deg corners.
e.g. Adelaide Place and Law Street in Dundee
**before, followed by after, in the same video:**
https://github.com/user-attachments/assets/bb8771c9-d3ad-4aa8-a9e2-819976630820
=> FIX: Diagonal filter rotation for acute intersections

web/src/App.svelte
=> Don't recreate the entire map component tree when changing basemaps.

web/src/locales/fr.po
First time doing that. Probably best by doing small iterations, especially depending on how the string lengths differences impact the UI.
=> Start French translation

web/src/title/TitleMode.svelte
This mostly affects local development, but theoretically could impact anywhere. There was a race condition where loading the project could happen before WASM is initialized.
=> Wait for WASM to be loaded before loading a project from URL

web/src/locales/fr.po
New "Hide small cells" options
Layers menu
=> A few more french translations
