backend/Cargo.lock
backend/Cargo.toml
backend/src/impact.rs
backend/src/lib.rs
backend/src/map_model.rs
backend/src/route.rs
backend/src/scrape.rs
backend/src/shortcuts.rs
web/src/App.svelte
web/src/ImpactDetailMode.svelte
web/src/NetworkMode.svelte
web/src/PredictImpactMode.svelte
web/src/ViewShortcutsMode.svelte
web/src/common/zorder.ts
web/src/stores.ts
web/src/wasm.ts

A start to #36. After some changes to one neighbourhood in Edinburgh:
The impact is mostly localized around there:
Justifying why Queen Street got busier with examples:

Start impact prediction mode

---

web/src/layers/OneWayLayer.svelte

I was just kind of exploring the maplibre svelte library and randomly saw this `interactive = false`, which seems to solve a problem you mentioned the other day @dabreegster.
Your clicks will no longer be "intercepted" by the 1-way layer symbols.
**before:** you can see the hover effect turn off for the road every time you hover over a 1-way glyph.
**after:**
But oops! The cursor is no longer what we want, so I had to specify the cursor for the 1-way layer. It's weird, but it seems to work. Do you know if we use the 1way layer in any non-interactive contexts where we *should not* show the pointer cursor?

Pass click events "through" non-interactive 1-way layer

---

backend/Cargo.lock
backend/src/create.rs
backend/src/geo_helpers.rs
backend/src/lib.rs
backend/src/map_model.rs
backend/src/movements.rs
web/src/DebugIntersectionsMode.svelte
web/src/ImpactDetailMode.svelte
web/src/ViewShortcutsMode.svelte
web/src/common/PrevNext.svelte
web/src/common/index.ts
web/src/common/zorder.ts
web/src/wasm.ts

Part of #30 (with some TODOs there) and also necessary for #41. This adds a debug mode (from the "pick neighbourhood" page) to understand movements at each intersection. They're generated by looking at one-way directions and the simplest OSM turn restriction cases. Only used in this debug mode right now, not yet for routing.
It's going to be much easier to flesh this out with a better unit testing story. I'm thinking of manually drawing / clipping some test cases in JOSM, checking those in here. For movements, maybe the output can be expressed in the code as a list of movements between named roads, or maybe some GeoJSON / SVG output would be faster to understand.

Start modelling movements at intersections

---

web/src/App.svelte

picocss is conflicting with maplibre - most notably the maplibre
controls have a silly amount of padding, so the controls look wonky.
Instead of applying picocss everywhere, we now "opt in" specific subtrees of
the DOM with the "pico" class.
It's kind of annoying, but it seems like it has to be this way -
if we're going to have two strong design systems (pico and maplibre),
they need to be confined to their own respective domains.
Note: it should be possible to use picocss within a tooltip/popup or something within the map, but we'd need to add a "pico" class to it.
**before:** Note how the zoom in/zoom out and search field controls in the map are very long.
**after:**

Fix layout of maplibre controls by only using pico in explicit parts of the layout.

---

.github/workflows/test.yml
backend/src/test_fixtures.rs
bin/download-local-dev-data.sh
bin/download-local-test-data.sh

#107 changed where the pbfs live, but we didn't update the unit tests, so those are failing locally now.
Ironically, because we *also* didn't change the CI script to match our new developer layout, CI continued to pass.
In #108 I added a script to download all the useful dev data. I wanted to use that script in CI to fetch data in the same way we're using it locally, but the dev data is quite large (500MB+), so I've broken out a `fetch_test_data` subscript that fetches only the data we need for testing (20MB or so).

Fix tests, CI fetches data with dev script

---

backend/src/lib.rs
backend/src/osm_tests/README.md
backend/src/osm_tests/deadend_with_barrier.osm.xml
backend/src/osm_tests/mod.rs
backend/src/osm_tests/no_left_turn.osm.xml

For #6 and #101 and other reasons, it'd be very useful to test the LTN tool on really simple, minimal inputs. I'm proposing we:
1) Draw something simple in iD -- it's quite quick:
2) Write small bits of code to assert things, instead of a more cumbersome visual diff test (which just tries to check too many things at once)
If this approach looks good, I've got some cases related to detecting filters in #6 I'll turn into tests.

Start some minimal OSM unit tests

---

web/src/AutoBoundariesMode.svelte

Completes #25 
Autodetection of neighborhood boundaries isn't **perfect** (and never will be), but it's "good enough" that at this point it makes sense to focus on manual tools like #130

remove debug info when hovering over neighborhood

---

web/src/CntChooseArea.svelte
web/src/common/HelpButton.svelte

Fixes #111 
Review note: you might want to hide whitespace diff

Work around pico-ambiguity

---

web/src/title/TitleMode.svelte

FIXES #117 
This is also responsible for the loading screen after creating a new CNT project, since the CNT project redirects you from ltn/cnt.html -> ltn/index.html.
**before:**
https://github.com/user-attachments/assets/3b846510-2c67-4cfd-9ed8-c7b9b0f0cadd
**after:**
https://github.com/user-attachments/assets/1fb9d9dd-ff06-44b0-94f2-eb356efae1ef
I still think the relationship between ltn/cnt.html and ltn/index.html could be made clearer, but this is a quick fix that improves thing in any case.

Add missing loading screen when loading from url

---

web/src/CntChooseArea.svelte

**before**:
https://github.com/user-attachments/assets/9c06c50a-d791-4900-8225-60177483e96c
**after**:
https://github.com/user-attachments/assets/3fd5318a-5ca5-407e-b734-b2933709a626
Note: this is a separate branch from #139, so there's no loading screen shown during the 5s loading period in the successful "after" video.

Redirect was broken when project name contained `#`

---

data_prep/scotland/get_reference_layers.sh
web/src/AutoBoundariesMode.svelte
web/src/common/zorder.ts
web/src/context/ContextualLayers.svelte
web/src/context/Population.svelte

#106 
You'll need to grab  https://assets.od2net.org/cnt_layers/population.pmtiles. I mistakenly uploaded an early draft of it during the first layers PR, but it's changed now.

Add contextual layers for SIMD and population density.

---

web/src/SetBoundaryMode.svelte

After fix:
See `invert_study_area_boundary` in Rust for how this feature is made in the first place.
It'd still be useful to reduce the waypoints to make this sanely editable. I've been meaning to write the same thing for NPW. Given the full desired geometry, come up with minimal waypoints that achieve the same thing.

Fix #149 for editing auto boundaries

---

web/src/App.svelte

Just a cute little UI flourish that helps establish where you *are* in the breadcrumb. This might be especially effective for red/green color blind people like me for which the current "link" colored text does little to differentiate.
https://github.com/user-attachments/assets/44f9a0c8-9f70-43d7-96a9-6b94f0919444

Make the *current* breadcrumb stand out

---

backend/Cargo.toml
backend/benches/boundary_stats.rs
backend/benches/build_neighbourhood.rs
backend/src/boundary_stats.rs
backend/src/create.rs
backend/src/map_model.rs
backend/src/neighbourhood.rs
backend/src/test_fixtures.rs

Followup to https://github.com/a-b-street/ltn/pull/166#discussion_r1966478092, to speed up the calculation using a prepared geometry.
```
build stats: LAD_Dundee City
time:   [1.8475 ms 1.8544 ms 1.8629 ms]
change: [-29.968% -29.750% -29.471%] (p = 0.00 < 0.05)
Performance has improved.
```
Feel free to squash these commits (or at least the Temporary/Revert ones)

Speed up boundary stats

---

Cargo.lock
Cargo.toml
backend/Cargo.toml
backend/benches/boundary_stats.rs
backend/src/boundary_stats.rs
backend/src/geo_helpers/slice_nearest_boundary.rs
web/src/AutoBoundariesMode.svelte
web/src/PickNeighbourhoodMode.svelte

It's about 10-15% slower to include buffering.  But it does significantly affect the results. Do you think it's worth it?
Personally I think we should. I think there is some performance work I can (would like to) do on the geo side to speed this up a bit, plus we can always pull out the buffering in the worst case if it proves intolerably slow.
**before:**
**after:**
Sorry, it's hard to tell, but I'm hovering the same boundary.
**before:**
**after:**

buffer neighbourhood stats

---

backend/src/boundary_stats.rs

Previously we were only preparing the population zones, not the boundary polygon itself.
But since we check *every* zone against the boundary, it makes sense to prepare the boundary.
Also a smaller change: Though we were correctly using PreparedGeometry for the Stats19 point check, we don't need to clone that geometry.
== BENCHMARKS
```
build stats: Hilltown in LAD_Dundee City
time:   [1.3602 ms 1.3667 ms 1.3746 ms]
change: [-43.356% -42.906% -42.448%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
2 (2.00%) high mild
Benchmarking generate auto boundaries (and stats) for all of LAD_Dundee City: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 46.4s, or reduce sample count to 10. …
```

Speed up BoundaryStats by preparing boundary polygon

---

web/src/About.svelte
web/src/App.svelte

Before, at high zoom, 3D building extrusions are a little visually noisy. I can't find a bad case right now, but sometimes the shadow even obscures roads that we're trying to color.
After, just use the flat 2D all the time:

Disable 3D buildings

---

web/src/layers/InteriorRoadLayer.svelte

Road center-lines meet at the same point, so when the lines are thickened in maplibre, the polygons overlap a bit.
Before, the lines are drawn in some arbitrary order (based on road IDs, just the order we scrape OSM data). White deadends with no shortcuts partly cover up red roads:
After, it looks a little cleaner in some places:

When two roads meet, draw the one with more shortcuts on top

---

web/src/edit/NeighbourhoodMode.svelte

A small touchup to clarify the "selected" state of the active tool.
**before: selected item is de-emphasized due to it being "disabled"**
https://github.com/user-attachments/assets/07392d54-ed9b-4c8c-bb5f-1aa573b354da
**after:**
https://github.com/user-attachments/assets/950d9270-2e35-4671-837a-3e51817a7085

Touch up tool palette UI

---

web/src/AutoBoundariesMode.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/common/SequentialLegendBucketed.svelte
web/src/common/colors.ts
web/src/context/Population.svelte
web/src/prioritization/PrioritizationSelect.svelte

FIXES #136 (mostly done before, but these are the final touches)
Some small tweaks based on our last meeting.
**before:**
**after:**

Adjust SIMD legend into quintiles and tweak copy

---

backend/src/map_model.rs
backend/src/route.rs

Cici spotted quite a notable bug:
An interior road right on the edge with a filter on it should not have any shortcuts! View shortcut mode reveals the problem is routes ending there:
Previously, I think we got away with this because of https://github.com/a-b-street/ltn/blob/00fb50bbedf1cb37606a54de99a91398a85e4c3e/backend/src/route.rs#L63. Roads with filters weren't part of the CH graph at all. But the change to `(road, direction)` pairs and handling all roads connected to the start/end intersection somehow let this slip in.

Fix routes incorrectly ending on a road with a modal filter

---

backend/src/auto_boundaries.rs

FIXES #145 (just the final bit)
I hadn't really considered this, but this actually has some (small) correctness implications for our prioritization aggregation:
**before:**
**after:**

Remove holes (lakes) from generated boundaries

---

web/cnt.html
web/src/App.svelte
web/src/AutoBoundariesMode.svelte
web/src/CntChooseArea.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/prioritization/PrioritizationSelect.svelte
web/src/stores.ts
web/src/title/NewProjectMode.svelte
web/src/title/TitleMode.svelte
web/src/title/loader.ts

FXIES #205 (part of #104)
This ended up not being a huge change (if you hide whitespace diff). In fact it got much smaller over time as I continued to work on it. But wow, each of these lines was hard fought.
Recall my first attempt was at https://github.com/a-b-street/ltn/issues/104#issuecomment-2658178251 which unified the `ltn` vs `ltn_cnt` landing pages, and introduced a dropdown to switch "app focus" between a "global" view and a "scotland" specific view. 
After talking it through with @dabreegster, it seems like that's not actually likely to reflect how cnt people will use the app. 
Where I landed, conceptually, is very similar from a datamodel perspective! We maintain an "appFocus" but now it's simply hardcoded by the root component based on the URL you access, e.g.: `App(element, …

Reconcile CNT vs. vanilla LTN landing pages

---

web/src/App.svelte
web/src/CntChooseArea.svelte
web/src/common/index.ts
web/src/title/LoadSavedProject.svelte
web/src/title/TitleMode.svelte
web/src/title/loader.ts

Fixes #195 
~~Diffbased on #211, please review that first.~~
Now both the global and CNT "choose project" pages have a tool to load a saved GJ file. From either of those pages, you can load any kind of file, and the app will switch to global or CNT mode accordingly... except for changing the URL.

Load saved CNT projects

---

web/src/ImpactOneDestinationMode.svelte
web/src/RouteMode.svelte
web/src/stores.ts
web/src/title/loader.ts

FIXES #72 
They are persisted, which is convenient when you want to see how your changes are affecting the route, but it's confusing, especially for new users, to see this route off screen.
Another thought I had, literally after I'd done all the work and was typing up the commit message:
Maybe another approach would be to leave the logic as is, and zoom out the bounds to encompass the markers.

Draggable route markers starts on screen.

---

web/src/ImpactDetailMode.svelte
web/src/PredictImpactMode.svelte
web/src/common/SequentialLegendBucketed.svelte
web/src/common/index.ts
web/src/common/zorder.ts
web/src/context/BusRoutes.svelte
web/src/context/CBD.svelte
web/src/context/POIs.svelte
web/src/context/Population.svelte
web/src/context/RailwayStations.svelte
web/src/context/RouteNetwork.svelte
web/src/context/Stats19.svelte
web/src/prioritization/PrioritizationSelect.svelte

- Workaround a bug where there are no example routes crossing somewhere
- Add a legend and outline the colors on the map
- Show neighbourhoods, for context where to expect green interior roads
Towards #36. Nothing in this mode here is really that nice yet, these're just little steps.
Before:
After:
---
I'm also thinking about optionally hiding or de-emphasizing some icons when zoomed. I'm having trouble seeing what's "important" here that the user did to cause all the changes shown:
If I hide unedited filters and TRs, the patterns of green and red in the neighbourhood make more intuitive sense:
Any opinions here?

Work on predict impact mode's visualization.

---

data_prep/scotland/src/bin/density_buckets.rs
data_prep/scotland/src/bin/generate_prioritization.rs
data_prep/scotland/src/lib.rs
web/src/common/colors.ts

FIXES #143 
Previously we were using density quintiles from the uk/wide census.
We had previously talked about doing something dynamic to scale quintiles per/study area, but I thought that Scotland-wide quintiles was an easier start, and an uncontroversial improvement.
(after on the left, before on the right)
**Glasgow:**
**Dundee:**
**Angus:**
For smaller communities, it's still a bit washed out. Dynamic quintiles would address that.
One downside of dynamic quintiles is that you'd lose the ability to compare density by color across maps, e.g. if you are looking at two maps. My guess is that isn't a huge problem though. Mainly I just like that this approach is simpler, and maybe "good enough".

Tune population density quintiles for Scotland

---

web/assets/map-styles/streets-v2-style.json
web/src/App.svelte
web/src/layers/CellLayer.svelte
web/src/stores.ts

FIXES #198 and a followup item mentioned in #220
Really, we could merge any subset of these commits. I tried to keep them separable.
Apart from the individual design changes, the big structural change is that I've vendored the maptiler style. 
Alternatively we could continue with the previous pattern of downloading and post-processing the given style, but as our diversions get more complex, it becomes increasingly hard to reason about. There's a reason these style files are declarative! 
I also think that it's totally reasonable that we are starting to develop our own cartography - the needs of our app are  special, and unique from some platonic "general purpose map".
**before:**
**after:** "main" roads are gray
**before:**
**after:**  most notable here is the relative building and cell …

cartographic delights

---

web/src/common/colors.ts
web/src/layers/NeighbourhoodRoadLayer.svelte

Now that we're coloring primary roads gray, let's avoid coloring other roads gray, so as not to confuse.
**before:**
**after:**

gray color should only be used for "main" roads

---

web/src/AutoBoundariesMode.svelte

hide non-existent stats from non-cnt users

---

.github/workflows/test.yml
web/package-lock.json
web/package.json
web/src/title/loader.test.ts
web/src/title/loader.ts
web/vite.config.ts
web/vitest.setup.ts

I broke this with some recent work around the storage layer (sorry!)
This was a read-only display issue - no data was permanently corrupted. After the update people should once again be able to load any custom areas they had previously defined.
**before:** Custom entries showed as "undefined"
**before:** Clicking on them would error.
**after:** custom entry in list
**after:** loading project succeeds
Also note: this introduces vitest to the development dependencies for web.

Fix loading custom areas

---

backend/src/impact.rs
web/src/ImpactDetailMode.svelte
web/src/ImpactOneDestinationMode.svelte
web/src/PredictImpactMode.svelte
web/src/RouteMode.svelte
web/src/common/DotMarker.svelte
web/src/context/ContextualLayers.svelte
web/src/layers/ModalFilterLayer.svelte
web/src/layers/TurnRestrictionLayer.svelte
web/src/stores.ts
web/src/wasm.ts

A few related changes.
#181 found a case where a route exists before edits, but not after. Previously we just showed the red "before" route, which was very confusing. Now it's hopefully more clear:
[Screencast from 16-03-25 14:07:11.webm](https://github.com/user-attachments/assets/ddc8e9b7-67d2-4d94-b274-9f737d6364d0)
Also, made the A/B dot markers orange instead of grey, since grey is pretty hard to spot and also means "main road" now.
Previously, when you hover on a road, you got a wall of text, and the blue/red routes were unlabeled mysteries. Now it's hopefully more clear:
Think that time ratio should also move to the sidebar and out of the popup? Or are there other things in this mode that don't feel easy to understand?
Part of #36. Previously, you would click some roads with changed …

Impact and route mode improvements

---

web/src/common/ContextLayerButton.svelte

The "existing modal filters and turn restrictions" label is long, and was causing its checkbox to be smooshed.
**before:**
**after:**

FIX: Layers checkbox getting smooshed sometimes.

---

backend/Cargo.toml
backend/benches/impact.rs
backend/src/create.rs
backend/src/impact.rs
backend/src/lib.rs
backend/src/map_model.rs
backend/src/od.rs
backend/src/test_fixtures.rs
web/src/AddNeighbourhoodMode.svelte
web/src/DebugDemandMode.svelte
web/src/ImpactDetailMode.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/PredictImpactMode.svelte
web/src/stores.ts
web/src/wasm.ts

Parts of #36 and #129.
- Impact prediction now has a loading screen to explain frozenness. If/when we manage to plumb progress info from the backend, this'd be the place to show it
- Link to the debug demand UI, reframing it slightly, since it does seem useful
- Let the user choose to either get a very fast-and-inaccurate prediction, or a slower-but-more-detailed prediction. We either sample one A -> B route from each data zone pair, or use as many points as the OD data says to.
Before, with the sampling, the impact of some changes to the center of Dundee:
After, without sampling, the visualization gets EXTREMELY noisy. Trips start and end all over the place, so practically every road sees some kind of change:
But actually, many of the changes are not interesting. A road going from 9 …

More features for impact prediction

---

web/src/common/QualitativeLegend.svelte
web/src/common/SequentialLegend.svelte
web/src/common/index.ts
web/src/context/CBD.svelte
web/src/context/POIs.svelte
web/src/context/Stats19.svelte

Fixes #231 
Addresses some of the crowding issues in the current legend layout.
The legend color swatches are now circles for POI and Collision data, which matches their cartographic symbology.
---
**POI before:** crowded squares
**POI after:** less crowded circles
---
**LoS before:** Labels are under limits
**LoS after:** Labels are under buckets
---
**Cycle infrastructure before:** crowded, label alignment is a little rough
**Cycle infrastructure after:** less crowded
---
**Collisions before:** not bad before (though I'd center the labels)
**Collisions after:** legend symbology matches map (circles). I also reversed the ordering - it seemed more intuitive.

Legend touchups

---

web/src/AddNeighbourhoodMode.svelte
web/src/CntChooseArea.svelte
web/src/common/ProjectStorage.test.ts
web/src/common/ProjectStorage.ts
web/src/common/pick_names.ts
web/src/title/LoadSavedProject.svelte
web/src/title/NewProjectMode.svelte
web/src/wasm.ts

FIXES #245 and #249 
We now suggest project and neighbourhood names, which makes the creation process a bit faster and a bit less "daunting" if you don't know what these names are for.
**New flow:**
https://github.com/user-attachments/assets/0135d3d2-10f3-4b4c-bbd1-2646206e9ddf
We're also stricter about not accepting blank names:
https://github.com/user-attachments/assets/40563284-2460-4fa8-b674-54f1c18c121b
Followup work: the "names must be non-empty" check is only enforced in the UI at creation time. Notably missing are:
1. a migration for existing "invalid" data
2. requiring names for projects loaded from JSON.
I don't anticipate that either of these would be especially hard, but it seemed lower priority, given that we don't actually rely on the names being non-empty as far as I know.

Suggest default project and neighborhood names, don't allow picking blank.

---

.github/workflows/test.yml

My typescript editor (usually vscode) doesn't inspect files unless they're in an open tab, so I sometimes don't see type errors for a while. 
e.g I originally opened #270 with a [type error](https://github.com/a-b-street/ltn/compare/de7396eb277963afa16e2534d8ab94d0370da70c..67b748f312d337cc746d801162a59484b59bd159) (In this case, it wasn't a real error, just something too confusing for typescript).

CI runs ts type checking

---

web/src/CntChooseArea.svelte
web/src/DebugNeighbourhoodMode.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/common/colors.ts
web/src/common/index.ts
web/src/layers/EditableIntersectionLayer.svelte
web/src/layers/NeighbourhoodRoadLayer.svelte

FIXES #237
**before:** On the pick neighbourhood screen currently, the pickable areas are colored gray, which communicates "disabled". E.g. we use the same gray color as a mask to "blot out" the rest of the world outside of the study area.
**after:**
https://github.com/user-attachments/assets/375f7795-ca20-4464-bd7b-8e0ee269b3c8
Now we use the same boundary outline style as used when building the neighbourhood boundary.
I think it's nice to throw back to the same design we use elsewhere to communicate neighbourhood boundaries.
I also think it's nice to match the "highlight" color on the map with the color we use in the sidebar when hovering.
I also like that the lack of mask when *not* hovered means you can see the interior of the neighbourhoods.
The major downside to this approach is …

FIX: "pick neighbourhood" shouldn't look disabled

---

backend/benches/boundary_stats.rs
backend/src/auto_boundaries.rs
backend/src/boundary_stats.rs
backend/src/create.rs
data_prep/scotland/build_cnt_lad_settlements.sh
data_prep/scotland/src/bin/generate_prioritization.rs

An attempt at https://github.com/a-b-street/ltn/issues/254#issuecomment-2744699163
FIXES #158 
FIXES #254
**before:** Largely rural areas (Highlands) had many huge, improbably, suggested boundaries, and ~30s load time.
Though it did look kind of fun.
**after:**
Zooming in to Inverness
Denser areas, e.g. Glasgow City are more or less unaffected by this change:
**before:**
**after:** Some of the outskirt neighborhoods seem to have an additional split, presumably when a previously "severance based" boundary is now split by the settlement boundary. I think that's fine:
If we decide to, I think adding buffering would be a straight forward change on top of this. But in my own QA, I haven't yet found cases where it would be helpful.
Performance diff:
```
inverness/generate auto boundaries (and …
```

Only generate boundaries within settlements.

---

web/src/CntChooseArea.svelte

There seems to be a bug in svelte-maplibre (or maplibre?). Presumably the issue is related to quickly switching between hovered features.
To reproduce pan into and out of one of the CNT boundaries. About 10% of the time, the background will not be colored appropriately for the hover state. Interestingly, the popup will still appear.
https://github.com/user-attachments/assets/5d4d9f0f-6a60-4537-af16-f698343f2d43
I cannot reproduce the issue after removing "hover" handling from the linestring borders. We don't need it anyway.
There is a similar seeming bug in the autgen boundaries page where occasionally, an empty popup appears. It seems slightly less reproducible, but still fairly common to see. I haven't figured that one out yet, but stay vigilant 👀.
Here's what that (unresolved issue) …

Fix occasionally missing hover state.

---

backend/src/lib.rs
backend/src/map_model.rs
backend/src/osm_tests/mod.rs
backend/src/test_fixtures.rs
web/src/App.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/common/HelpButton.svelte
web/src/common/ProjectStorage.test.ts
web/src/common/ProjectStorage.ts
web/src/common/index.ts
web/src/title/LoadSavedProject.svelte
web/src/title/NewProjectMode.svelte
web/src/title/TitleMode.svelte
web/src/title/loader.ts
web/src/wasm.ts

FIXES #138 
Also, some related UI work:
Added a "quick" (redundant) download button on the project picker table:
---
And with the pre-existing export project button:
**before:** export project button at the bottom of the project details.
**after:** export project button at the top, in line with the project name.
I'm not entirely clear about this change. 
It's a little more economical from a vertical space perspective (which is a hot commodity in our UI!)
I think it better mirrors the new "quick" download button. Conceivably we could mirror the other actions here too, in particular "rename project", but maybe also "delete project".

Include schema version in savefile

---

web/src/layers/CellLayer.svelte

@XioNoX just proposed slightly fading the border arrows to be able to see underneath them in #287. I tried this, and think it still looks legible but now lets you see grey / not-grey roads underneath:
Before the full approach in #279, how about we do this as a workaround. I'll ASAP merge this to unblock users having this problem, and we can adjust easily later.

Temporarily fade the border arrows to mitigate #279.

---

web/src/layers/NeighbourhoodRoadLayer.svelte

FIXES #290 
This is a partial revert of https://github.com/a-b-street/ltn/commit/49629fec0a0d543a69929b9cd64e5ba5115eb464#diff-eb72a5e7f5a0b04e27ba1e11c412351855e54f41c1ca662fb0556dc652d818a5R100
Which introduced manually marking/unmarking a road as a "main road".
@dabreegster - do you recall why adding this option was necessary. In my testing I'm still able to mark/unmark roads without this option. If we need it, I'll have to come up with another way to resolve the issue.

FIX: adding diagonal filter also adds modal filter

---

web/src/Settings.svelte
web/src/edit/NeighbourhoodMode.svelte

Part of #121 
This setting only affects the map in NeighbourhoodMode anyway. It fits nicely along side options like "Animate shortcuts" and "Show entires into cells".
I also applied a "footnote" style to the Cells and Shortcut "definitions" in the Map style copy.
**before:** Road thickness depends on shortcuts was in the "global settings" menu in the title bar.
**before:** Map style within neighborhoods:
**After:** "Road thickness..." moved into map style
Also, put the "road style" control on a single line, which obviates the need for a border.
I also restyled the definitions as "footnotes", since they were a little awkward inline, and could apply to multiple settings. And tweaked the cells copy to mention "colored". WDYT?

move road thickness "setting" to neighourhood -> "map style"

---

web/src/edit/NeighbourhoodMode.svelte

Followup to https://github.com/a-b-street/ltn/pull/296#discussion_r2026648187
pico tooltip styling is pretty brutal for longer content, so I had to add some special handling to allow for reasonable word wrap.

Put the footnote text into tooltips to save space.

---

web/src/common/ContextLayerButton.svelte
web/src/context/ContextualLayers.svelte

FIXES #276 
**Before:** Scrolling down would scroll the header out of view, so it was harder to minimize the layer controls
**After:** Content scrolls behind the header, so you can always minimize the layers
I also changed the color scheme to be more neutral - the previous colors were based on the "pico secondary" button styles which feel very heavy to me. 
I don't feel super strongly about that part of the change though. I put it into a separate commit so you could easily revert it if you prefer something closer to the old colors.

Layer control: small design improvements

---

web/src/App.svelte
web/src/common/StreetView.svelte

FIXES #121 (last item in the grab bag)
**before:** these controls were on every screen in the left panel
**after:** Now they're on the map panel, along side our other map controls
**flow:**
https://github.com/user-attachments/assets/e4b8376e-8ad8-450f-a1ad-7680bc1b38f1
Changing the "eye" icon when the configuration is presented is somewhat silly, but I think it helps communicate that the button has two states. Click it again to close it and return to the default state.

Move map controls to map

---

backend/src/lib.rs
web/src/AddNeighbourhoodMode.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/SetBoundaryMode.svelte
web/src/common/ModeLink.svelte
web/src/common/ProjectStorage.test.ts
web/src/common/ProjectStorage.ts
web/src/common/navbar.ts
web/src/edit/NeighbourhoodMode.svelte
web/src/stores.ts
web/src/wasm.ts

FIXES #280 
Based on #312, so review that first.
https://github.com/user-attachments/assets/e0ebef46-e055-4a4d-9a79-9ab104c3f8bc
(🤦 Note how I tried to click "Choose Area" instead of "Create neighborhood" at 00:12s. I should copy the "active tool" style from the edit tools, I'll do that right now, should be quick).
Here's how the breadcrumbs look with a pathologically long name on a very narrow screen:
If it's an "inner" breadcrumb, we truncate it:
If it's the final breadcrumb (the current page), we unfurl the full name in all its glory - so the user can see the full name.
Not great... but there's only so much we can do!
Note: The max-size is defined in units of `vw`, so we'll truncate less on wider screens.
---
Also: With the project and neighbourhood names in the breadcrumb, their …

better breadcrumbs

---

backend/src/boundary_stats.rs
data_prep/scotland/get_reference_layers.sh
data_prep/scotland/src/bin/generate_prioritization.rs
web/src/context/POIs.svelte

FIXES #233 
We should have sustrans take a sanity pass at our categories.
Zooming in you can see how the recreation POI's often correspond with the map data POIs
I was tempted to add restaurants and fast_food, as they are likely destinations, but I couldn't justify filing taco bell under recreation.

Recreation POIs

---

backend/src/lib.rs
backend/src/neighbourhood.rs
web/src/SetBoundaryMode.svelte
web/src/wasm.ts

FIXES #201 
You can create your neighbourhood "by hand" or by picking from a set of generated "severance" blocks.
Typically starting with the generated severance blocks is easier, but it's common that you also want to tweak the boundary a little bit to include/exclude some roads on the edge.
Adjust boundaries means manipulating the placement of Waypoints. For hand-drawn neighbourhoods, this is easy - we store the Waypoints placed by the user when they were drawing the neighbourhood initially.
For generated boundaries this is trickier. Previously, we simply generated a waypoint for every single vertex in the polygon. Because these shapes could be a bit complex, we'd easily end up with hundreds of waypoints. In practice, editing one of these neighbourhoods was very tedious.
The change here, …

Simplify generated waypoints from "picked" neighbourhoods.

---

web/package-lock.json
web/package.json
web/src/App.svelte
web/src/common/PrevNext.svelte
web/src/common/index.ts
web/src/edit/NeighbourhoodMode.svelte

Instead employ tippy.js
picocss tooltips were nice because they were completely declarative. However plain css wasn't powerful enough - we need more information about the current layout to position the tooltip visibly in some cases, which requires js.
Specific examples:
1. The "Add modal filter" button, had its tooltip mostly off the left edge of the screen.
2. Symmetrically, the "Redo" button, had its tooltip cropped off by the right edge of the left panel.
3. The "Redo" button and the "footnote" tooltips caused the left panel to be wider than necessary, even when they weren't being displayed, which introduced an undesirable (and very hard to track down!!!) horizontal scroll in the left panel.
The downside to this new non-declarative approach is that every component needs to initialize …

Fix: tooltips off screen and introduce undesirable scrolling

---

web/src/AddNeighbourhoodMode.svelte
web/src/App.svelte
web/src/PickNeighbourhoodMode.svelte
web/src/edit/NeighbourhoodMode.svelte
web/src/prioritization/PrioritizationSelect.svelte

Based on #326 so merge that first.
Part of #304 
There's a handful of related changes here. I've done some QA, but it's not impossible that there are some new layout regressions.
**before: medium**
**after: medium**
**before: wide**
**after: wide**
**before: narrow**
**after: narrow**

smaller left panel

---

backend/src/cells.rs

FIXES #322.
Here's a quick test case:
[diag cells-2025-04-12.geojson.txt](https://github.com/user-attachments/files/19721695/diag.cells-2025-04-12.geojson.txt)
Before, there's one big cell.
After, the cells reflect the possible movements.

Take diagonal filters in account for cells

---

web/src/common/ContextLayerButton.svelte
web/src/prioritization/PrioritizationSelect.svelte

I think right-aligning cleans this up visually, what do you think?
Before:
After:

Right-align help buttons

---

web/src/title/NewProjectMode.svelte
web/src/title/loader.ts

I noticed something pretty awkward. Open up the dev console and create a new project from Overpass. Previously, we were downloading + importing, then immediately doing the same thing again due to calling `loadProject`. I've fixed this, verifying the console logs and making sure the new project created behaves correctly (saving changes, refreshing and loading it, etc)

When importing a new custom area, don't download and import twice

---

data_prep/scotland/src/bin/generate_prioritization.rs
data_prep/scotland/src/lib.rs

This isn't really a big deal, but a followup to #330 
By using the PopulationZoneInput:
1. We already have area, so we can skip building up and passing in a reduntant area_km2 vec.
2. We already have a prepared geometry.
And a minor pedantic improvement, by constructing the MetricBuckets before the ContextData, we can avoid initializing with a temporary bogus `Default` value.

Clean up generate_prioritization

---

web/src/AddNeighbourhoodMode.svelte
web/src/App.svelte
web/src/common/ContextLayerButton.svelte
web/src/common/ModeLink.svelte
web/src/context/CBD.svelte
web/src/context/ContextualLayers.svelte
web/src/context/Population.svelte
web/src/context/RouteNetwork.svelte

A few unrelated things:
1) Disable map rotation entirely. It's too easy to do accidentally and unclear how to undo, especially when you tilt. I don't think I've ever seen any reason to use it.
2) Rename a button per Cici's recommendation
3) Rename and group layers based on Cici's recommendation
4) Fix #147, keeping checkbox styling for consistency/simplicity

Contextual layer tweaks

---

web/src/common/MetricProgress.svelte
web/src/common/NeighbourhoodBoundarySummary.svelte
web/src/common/colors.ts
web/src/prioritization/PrioritizationSelect.svelte
web/src/prioritization/index.ts

FIXES #191.
[Screencast from 25-04-25 17:57:01.webm](https://github.com/user-attachments/assets/e9130ba5-9f62-46b3-a2c0-7af8c659a0b3)
I've gone with a "progress bar" that shows the bucket colors. Cici and Angus liked this enough.
Note car ownership and SIMD are still reversed relative to the other metrics; I'll fix that separately. Showing the colors makes things explicit, in the meantime.

Show simple progress bars for the neighbourhood stats summary

---

web/src/common/ContextLayerButton.svelte
web/src/common/zorder.ts
web/src/context/Stats19.svelte

The sea of stats19 dots (with popups!) at low zoom isn't helpful. Switch to a heatmap instead. I've mostly kept maplibre's default heatmap styling, but adjusted the clustering slightly to look decent in both sparse and dense areas. Happy to do more tuning though!
(Videos are hitting the 10MB limit too quickly, with so much on the screen)

Heatmap for collisions

---

backend/src/geo_helpers/mod.rs
backend/src/lib.rs
backend/src/neighbourhood.rs

FIXES #257 
[Screencast from 29-04-25 09:58:06.webm](https://github.com/user-attachments/assets/bb0f61b3-0ccd-4a8a-b4ee-f3122e71f23f)
The behavior in debug mode feels correct to me here. The 3 points don't form a valid area for this odd case, because they just double back to try and connect. It feels intuitive to me to have the left sidebar reflect that I haven't made a valid area yet.

Cleanly handle one error case when drawing boundaries

---

web/src/edit/NeighbourhoodMode.svelte

A simple start to #345 -- roughly halve the time after every edit, unless the user has opted into animating shortcuts. For huge/slow areas, I don't believe anybody reasonably would. So should be an immediately noticeable boost.

Don't calculate shortcuts unless we're animating

---

web/src/About.svelte
web/src/title/TitleMode.svelte

More clear branding has been requested, so in CNT mode:

Rebrand the tool for CNT

---

backend/src/lib.rs
backend/src/map_model.rs
backend/src/neighbourhood.rs
backend/src/render_cells.rs
web/src/edit/NeighbourhoodMode.svelte
web/src/wasm.ts

It's totally possible to manually draw an area that has no main roads at all. Previously there was a popup error, but with this PR, it's now possible, but the result is pretty boring, because there are no shortcuts.
The real use of this is with a new button to erase all main roads at once. If you're working on a circulation plan in a huge area like this, using the eraser tool or manually clicking all of the main roads on the inside is really, really tedious:
It's easier in this case to just blank out all the main roads, then draw only the main roads around the outside, and any on the inside that should retain through-traffic. We can call out this special use case in the user guide.

Handle edge cases with no main roads

---

web/src/PickNeighbourhoodMode.svelte

show them an empty pick screen
We've had a few bits of confused feedback from people loading an empty project and not understanding what to do (despite the primary "add neighbourhood" button. So just forcibly prevent people from winding up on this screen without anything defined.

If a user loads an empty project or deletes all neighbourhoods, don't

---

.gitignore
Cargo.lock
README.md
backend/Cargo.toml
backend/src/test_fixtures.rs
bin/download-local-dev-data.sh
data_prep/.gitignore
data_prep/scotland/README.md
data_prep/scotland/build_all_areas.sh
data_prep/scotland/geojson_to_osmium_extracts.py
data_prep/scotland/get_reference_layers.sh
data_prep/scotland/src/bin/generate_od.rs
data_prep/scotland/src/bin/generate_prioritization.rs
web/src/App.svelte
web/src/context/BusRoutes.svelte
web/src/context/CBD.svelte
web/src/context/Population.svelte
web/src/context/RailwayStations.svelte
web/src/context/RouteNetwork.svelte
web/src/context/Stats19.svelte
web/src/stores.ts
web/src/title/loader.ts

FIXES #239 and #255
This PR reorganizes the directory structure for CNT assets, from the repetitive "cnt_demand/demand_LAD_foo.bin" structure to "cnt/demand/LAD_foo.bin.gz". Nesting all the CNT directories in one "cnt/" directory lets me organize my local cache of cloudflare R2 locally and have a script to sync it properly.
And secondly, this PR gzips most assets, achieving a big reduction in download time. Browsers will magically gunzip before handing to WASM, thanks to the `content-encoding: gzip` header. For future reference, to get this served by cloudflare (objects stored in R2, with a custom domain `assets.cnt.scot` wired up), it appears impossible to use `rclone`, despite vague docs online suggesting otherwise. After uploading the gzipped objects, I'm doing something like this to …

Reorganize CNT asset storage and gzip most files

---

backend/src/lib.rs
backend/src/map_model.rs
web/src/common/zorder.ts
web/src/edit/NeighbourhoodMode.svelte
web/src/edit/ShowBeforeEdits.svelte
web/src/layers/CellLayer.svelte
web/src/layers/EditableIntersectionLayer.svelte
web/src/layers/ModalFilterLayer.svelte
web/src/layers/NeighbourhoodRoadLayer.svelte
web/src/layers/OneWayLayer.svelte
web/src/layers/TurnRestrictionLayer.svelte
web/src/stores.ts
web/src/wasm.ts

Fixes most of #376.
This introduces a new control to revert all edits and just display the original state of a neighbourhood, so the user can quickly compare.
[Screencast from 13-06-25 08:38:01.webm](https://github.com/user-attachments/assets/912869e8-6465-4ff3-9110-b84e1643e4e1)
Try it out: https://a-b-street.github.io/ltn/before_after_V2
@XioNoX and @TFCx, please see if this achieves what you're trying to do
Questions:
- Is the "Draw roads: edits (either filter or direction)" still useful after this? I think maybe so, if it's a complex area
- From discussion: YES, keep it
- Does it make sense to also show the original main road classification? Do you ever want to see shortcuts on a current main road, but without any new filters?
- From discussion: It could be useful sometimes to see the …

Show a neighbourhood before edits

---

.github/workflows/web.yml
web/package-lock.json
web/package.json
web/src/App.svelte
web/src/wasm.ts
web/vite.config.ts

This is a prereq to attempting a Svelte 5 upgrade (for #404). The old vite-plugin-wasm-pack plugin has been partly broken from when I first started using it a few years ago; the latest published version has never worked. vite-plugin-wasm is the newer thing compatible with modern Vite.

Switch to vite-plugin-wasm and update vite
